function d = great_circ_dist(r, az1, az2, el1, el2)

    d_az = abs(az1-az2);
    d = r * atan2d( ...
                sqrt( (cosd(el2).* sind(d_az)).^ 2 ...
                     +(cosd(el1).*sind(el2) ...
                        - (sind(el1).*cosd(el2).*cosd(d_az))).^2), ...
                 sind(el1).* sind(el2) ...
                 + cosd(el1).* cosd(el2).*cosd(d_az));

end